name: Publish Shared Lib

on:
  push:
    branches:
      - main
    paths:
      - 'projects/shared-lib/**'
      - '.github/workflows/publish.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@bookstore-app'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:prod

      - name: Publish to NPM
        run: |
          cd dist/shared-lib
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Trigger reports action
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOOKSTORE_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'book-store-mfe',
              repo: 'shared-lib',
              workflow_id: 'report.yml',
              ref: 'main'
            })
