name: Publish Shared Lib

on:
  push:
    branches:
      - main
    paths:
      - 'projects/shared-lib/**'
      - '.github/workflows/publish.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@bookstore-app'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:prod

      - uses: JS-DevTools/npm-publish@v3
        run: npx npm-publish --token ${{ secrets.GITHUB_TOKEN }} dist/shared-lib --access public
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"

