name: Send Report

on:
  workflow_dispatch:

jobs:
  trigger-report:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger smoke tests actions in reports repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOOKSTORE_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'book-store-mfe',
              repo: 'reports',
              workflow_id: 'smoke-tests.yml',
              ref: 'main'
            })
